# Generated by Django 5.0.6 on 2024-06-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_employees_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table=None,
        ),
    ]
