# Generated by Django 5.0.6 on 2024-07-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=25)),
                ('job', models.CharField(max_length=15)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
