# Generated by Django 5.0.6 on 2024-08-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('python', models.FloatField()),
                ('html', models.FloatField()),
                ('javascript', models.FloatField()),
            ],
        ),
    ]
